# Site settings
title: PyLadies Brasil
email: brazil@pyladies.com
description: "Nós somos um grupo internacional com foco em ajudar mais mulheres a se tornarem participantes ativas e líderes de comunidades Python."
baseurl: ""
url: "http://pyladiesbrasil.com"

# Build settings
markdown: kramdown
permalink: pretty

